prevent commit on main branch (#71)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,9 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+if [ `git branch --show-current` == "main" ]; then
+  echo "Cannot make local commit on main branch!"
+  exit 1
+fi
+
 cd frontend && npm run lint && npm run format
