make go build -n silent

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -31,9 +31,11 @@ jobs:
       run: |
         go vet ./...
         go fmt ./...
+        # src of the code below: https://developers.wano.co.jp/1883/
+        git diff --exit-code --quiet
+        if [ $? -eq 0 ]; then echo "Go vet and fmt passed"; else echo "Go vet or fmt failed"; exit 1; 
         go run honnef.co/go/tools/cmd/staticcheck@latest ./...
         go test -v ./...
-        go build -n
-        # src of the code below: https://developers.wano.co.jp/1883/
+        go build -n >/dev/null
         git diff --exit-code --quiet
         if [ $? -eq 0 ]; then echo "ok"; else echo "git diff error"; exit 1; 
