delete sleep 10

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -30,7 +30,7 @@ jobs:
       working-directory: ./backend/
       run: |
         # src of the code below: https://developers.wano.co.jp/1883/ (modified)
-        function assert_no_change () { git diff --exit-code --quiet; if [ $? -eq 0 ]; then echo "Go tests: $1 passed"; else echo "Go tests: $1 failed"; sleep 10; exit 1; fi }
+        function assert_no_change () { git diff --exit-code --quiet; if [ $? -eq 0 ]; then echo "Go tests: $1 passed"; else echo "Go tests: $1 failed"; exit 1; fi }
         :
         echo Starting go vet...
         go vet ./...
